/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRequestRouteImport } from './routes/reset-password-request'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as PlayFreeRouteImport } from './routes/play-free'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicCronSettleLeaderboardRouteImport } from './routes/api/public/cron/settle-leaderboard'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRequestRoute = ResetPasswordRequestRouteImport.update({
  id: '/reset-password-request',
  path: '/reset-password-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFreeRoute = PlayFreeRouteImport.update({
  id: '/play-free',
  path: '/play-free',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSettleLeaderboardRoute =
  ApiPublicCronSettleLeaderboardRouteImport.update({
    id: '/api/public/cron/settle-leaderboard',
    path: '/api/public/cron/settle-leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/play-free': typeof PlayFreeRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-request': typeof ResetPasswordRequestRoute
  '/signup': typeof SignupRoute
  '/slots': typeof SlotsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/cron/settle-leaderboard': typeof ApiPublicCronSettleLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/play-free': typeof PlayFreeRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-request': typeof ResetPasswordRequestRoute
  '/signup': typeof SignupRoute
  '/slots': typeof SlotsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/cron/settle-leaderboard': typeof ApiPublicCronSettleLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/play-free': typeof PlayFreeRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-request': typeof ResetPasswordRequestRoute
  '/signup': typeof SignupRoute
  '/slots': typeof SlotsRoute
  '/trade': typeof TradeRoute
  '/wallet': typeof WalletRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/cron/settle-leaderboard': typeof ApiPublicCronSettleLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/leaderboard'
    | '/login'
    | '/missions'
    | '/play-free'
    | '/refer'
    | '/reset-password'
    | '/reset-password-request'
    | '/signup'
    | '/slots'
    | '/trade'
    | '/wallet'
    | '/auth/callback'
    | '/api/public/cron/settle-leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/leaderboard'
    | '/login'
    | '/missions'
    | '/play-free'
    | '/refer'
    | '/reset-password'
    | '/reset-password-request'
    | '/signup'
    | '/slots'
    | '/trade'
    | '/wallet'
    | '/auth/callback'
    | '/api/public/cron/settle-leaderboard'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/leaderboard'
    | '/login'
    | '/missions'
    | '/play-free'
    | '/refer'
    | '/reset-password'
    | '/reset-password-request'
    | '/signup'
    | '/slots'
    | '/trade'
    | '/wallet'
    | '/auth/callback'
    | '/api/public/cron/settle-leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  PlayFreeRoute: typeof PlayFreeRoute
  ReferRoute: typeof ReferRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetPasswordRequestRoute: typeof ResetPasswordRequestRoute
  SignupRoute: typeof SignupRoute
  SlotsRoute: typeof SlotsRoute
  TradeRoute: typeof TradeRoute
  WalletRoute: typeof WalletRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicCronSettleLeaderboardRoute: typeof ApiPublicCronSettleLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password-request': {
      id: '/reset-password-request'
      path: '/reset-password-request'
      fullPath: '/reset-password-request'
      preLoaderRoute: typeof ResetPasswordRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-free': {
      id: '/play-free'
      path: '/play-free'
      fullPath: '/play-free'
      preLoaderRoute: typeof PlayFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/settle-leaderboard': {
      id: '/api/public/cron/settle-leaderboard'
      path: '/api/public/cron/settle-leaderboard'
      fullPath: '/api/public/cron/settle-leaderboard'
      preLoaderRoute: typeof ApiPublicCronSettleLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  PlayFreeRoute: PlayFreeRoute,
  ReferRoute: ReferRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetPasswordRequestRoute: ResetPasswordRequestRoute,
  SignupRoute: SignupRoute,
  SlotsRoute: SlotsRoute,
  TradeRoute: TradeRoute,
  WalletRoute: WalletRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicCronSettleLeaderboardRoute: ApiPublicCronSettleLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
